# Generated by Django 5.2.13 on 2026-04-17 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Apartamento'), ('commercial', 'Comercial'), ('land', 'Terreno')], max_length=20)),
                ('listing_type', models.CharField(choices=[('sale', 'Venda'), ('rent', 'Aluguel')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('parking_spots', models.PositiveSmallIntegerField(default=0)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('address_line', models.CharField(max_length=512)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'db_table': 'property_images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
